server:
  port: 8080
spring:
  application:
    name: @project.artifactId@
management:
  server:
    port: 8081
jenkins:
  usernamePassword: true
  usernameApiToken: false
  anonymous: false
  username: fenxx
#  credential: 11def70e9xx9a
  url: http://10.xx080
  credential: SbxxsQh
file:
  upload:
    path: /ac/jenkins/plugins
    allowTypes:
      - application/octet-stream